version: '3'
services:
  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db_storage:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
  web:
    container_name: web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - selenium_chrome
    environment:
      DATABASE_PASSWORD: pass
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - 4444:4444
volumes:
  db_storage:
