name: Deploy to Heroku
on:
  push:
    branches:
      - main

jobs:
  rspec_and_rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run services
        run: docker-compose up --build -d

      - name: Wait for MySQL
        run: docker-compose exec -T db bash -c 'until mysqladmin ping -h "db" --silent; do sleep 1; done'

      - name: Create test database
        run: docker-compose exec -T web bundle exec rails db:create RAILS_ENV=test

      - name: Run migrations
        run: docker-compose exec -T web bundle exec rails db:migrate RAILS_ENV=test

      - name: Precompile Assets
        run: docker-compose exec -T web bundle exec rails assets:precompile

      - name: Run RSpec
        run: docker-compose exec -T web bundle exec rspec

      - name: Run Rubocop
        run: docker-compose exec -T web bundle exec rubocop --require rubocop-airbnb

  deploy_to_heroku:
    runs-on: ubuntu-latest
    needs: rspec_and_rubocop

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Heroku Container Registry
        run: echo "$HEROKU_API_KEY" | docker login --username="$HEROKU_EMAIL" --password-stdin registry.heroku.com

      - name: Build Docker image
        run: docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .

      - name: Push Docker image to Heroku
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Release the Docker image on Heroku
        run: |
          heroku auth:token | docker login --username=_ --password-stdin registry.heroku.com
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
          heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}

      - name: Notify Deployment Success
        run: echo "Deployment to Heroku successful!"

  # deploy_to_heroku:
  #   runs-on: ubuntu-latest
  #   needs: rspec_and_rubocop

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Login to Heroku
  #       uses: akhileshns/heroku-deploy@v3.12.12
  #       with:
  #         heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
  #         heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
  #         heroku_email: ${{ secrets.HEROKU_EMAIL }}
  #         usedocker: true
