name: Deploy to Heroku
on:
  push:
    branches:
      - main

jobs:
  rspec_and_rubocop:
    runs-on: ubuntu-latest
    env:
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 3.1.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4

      - name: Set Rails_ENV
        run: echo "RAILS_ENV=test" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          sudo apt-get -yqq install libsqlite3-dev
          bundle install
          bin/rails db:create
          bin/rails db:migrate
          bin/yarn install

      - name: Run Rubocop
        run: bundle exec rubocop --require rubocop-airbnb

      - name: Run RSpec
        run: bundle exec rspec

  deploy_to_heroku:
    runs-on: ubuntu-latest
    needs: rspec_and_rubocop

    steps:
      - uses: actions/checkout@v2

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: "xs_caster@yahoo.co.jp"
