name: Deploy to Heroku
on:
  push:
    branches:
      - main

jobs:
  rspec_and_rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run services
        run: docker-compose up --build -d

      - name: Run RSpec
        run: docker-compose exec web bundle exec rspec

      - name: Run Rubocop
        run: docker-compose exec web bundle exec rubocop --require rubocop-airbnb

  deploy_to_heroku:
    runs-on: ubuntu-latest
    needs: rspec_and_rubocop

    steps:
      - uses: actions/checkout@v2

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: "xs_caster@yahoo.co.jp"
